
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_FAILER = "SET_USER_FAILER";
export const SET_USER_SUCCESS = "SET_USER_SUCCESS";

export const SET_USER_LOGIN_START = "SET_USER_LOGIN_START";
export const SET_USER_LOGIN_FAILER = "SET_USER_LOGIN_FAILER";
export const SET_USER_LOGIN_SUCCESS = "SET_USER_LOGIN_SUCCESS";

export const SET_USER_LOGOUT_SUCCESS = "SET_USER_LOGOUT_SUCCESS";

export const SET_USER_REGISTRATION_START = "SET_USER_REGISTRATION_START";
export const SET_USER_REGISTRATION_FAILER = "SET_USER_REGISTRATION_FAILER";
export const SET_USER_REGISTRATION_SUCCESS = "SET_USER_REGISTRATION_SUCCESS";



export const FETCH_TYPES_START = "FETCH_TYPES_START";
export const FETCH_TYPES_FAILER = "FETCH_TYPES_FAILER";
export const FETCH_TYPES_SUCCESS = "FETCH_TYPES_SUCCESS";

export const CREATE_DEVICE_TYPE_START = "CREATE_DEVICE_TYPE_START";
export const CREATE_DEVICE_TYPE_FAILER = "CREATE_DEVICE_TYPE_FAILER";
export const CREATE_DEVICE_TYPE_SUCCESS = "CREATE_DEVICE_TYPE_SUCCESS";

export const GET_GLOBAL_TYPES = "GET_GLOBAL_TYPES";
export const REMOVE_GLOBAL_TYPES = "REMOVE_GLOBAL_TYPES";

export const GET_GLOBAL_SORTING_TYPES = "GET_GLOBAL_SORTING_TYPES";
export const REMOVE_GLOBAL_SORTING_TYPES = "REMOVE_GLOBAL_SORTING_TYPES";

export const GET_GLOBAL_SORTING_TABLE = "GET_GLOBAL_SORTING_TABLE";
export const REMOVE_GLOBAL_SORTING_TABLE = "REMOVE_GLOBAL_SORTING_TABLE";

export const GET_GLOBAL_PAGINATION = "GET_GLOBAL_PAGINATION";
export const REMOVE_GLOBAL_PAGINATION = "REMOVE_GLOBAL_PAGINATION";



export const GET_GLOBAL_BRAND = "GET_GLOBAL_BRAND";
export const REMOVE_GLOBAL_BRAND = "REMOVE_GLOBAL_BRAND";

export const FETCH_BRAND_START = "FETCH_BRAND_START";
export const FETCH_BRAND_FAILER = "FETCH_BRAND_FAILER";
export const FETCH_BRAND_SUCCESS = "FETCH_BRAND_SUCCESS";

export const CREATE_DEVICE_BRAND_START = "CREATE_DEVICE_BRAND_START";
export const CREATE_DEVICE_BRAND_FAILER = "CREATE_DEVICE_BRAND_FAILER";
export const CREATE_DEVICE_BRAND_SUCCESS = "CREATE_DEVICE_BRAND_SUCCESS";


export const FETCH_DEVICE_START = "FETCH_DEVICE_START";
export const FETCH_DEVICE_FAILER = "FETCH_DEVICE_FAILER";
export const FETCH_DEVICE_SUCCESS = "FETCH_DEVICE_SUCCESS";

export const FETCH_ONE_DEVICE_START = "FETCH_ONE_DEVICE_START";
export const FETCH_ONE_DEVICE_FAILER = "FETCH_ONE_DEVICE_FAILER";
export const FETCH_ONE_DEVICE_SUCCESS = "FETCH_ONE_DEVICE_SUCCESS";

export const CREATE_DEVICE_START = "CREATE_DEVICE_START";
export const CREATE_DEVICE_FAILER = "CREATE_DEVICE_FAILER";
export const CREATE_DEVICE_SUCCESS = "CREATE_DEVICE_SUCCESS";

export const UPDATE_DEVICE_PRICE_START = "UPDATE_DEVICE_PRICE_START";
export const UPDATE_DEVICE_PRICE_FAILER = "UPDATE_DEVICE_PRICE_FAILER";
export const UPDATE_DEVICE_PRICE_SUCCESS = "UPDATE_DEVICE_PRICE_SUCCESS";


export const FETCH_PROCESSORS_START = "FETCH_PROCESSORS_START";
export const FETCH_PROCESSORS_FAILER = "FETCH_PROCESSORS_FAILER";
export const FETCH_PROCESSORS_SUCCESS = "FETCH_PROCESSORS_SUCCESS";

export const GET_GLOBAL_PROCESSOR = "GET_GLOBAL_PROCESSOR";
export const REMOVE_GLOBAL_PROCESSOR = "REMOVE_GLOBAL_PROCESSOR";

export const CREATE_DEVICE_PROCESSOR_START = "CREATE_DEVICE_PROCESSOR_START";
export const CREATE_DEVICE_PROCESSOR_FAILER = "CREATE_DEVICE_PROCESSOR_FAILER";
export const CREATE_DEVICE_PROCESSOR_SUCCESS = "CREATE_DEVICE_PROCESSOR_SUCCESS";

export const UPDATE_PROCESSOR_PRICE_START = "UPDATE_PROCESSOR_PRICE_START";
export const UPDATE_PROCESSOR_PRICE_FAILER = "UPDATE_PROCESSOR_PRICE_FAILER";
export const UPDATE_PROCESSOR_PRICE_SUCCESS = "UPDATE_PROCESSOR_PRICE_SUCCESS";


export const CREATE_COMPUTER_CASE_START = "CREATE_COMPUTER_CASE_START";
export const CREATE_COMPUTER_CASE_FAILER = "CREATE_COMPUTER_CASE_FAILER";
export const CREATE_COMPUTER_CASE_SUCCESS = "CREATE_COMPUTER_CASE_SUCCESS";

export const UPDATE_COMPUTER_CASE_PRICE_START = "UPDATE_COMPUTER_CASE_PRICE_START";
export const UPDATE_COMPUTER_CASE_PRICE_FAILER = "UPDATE_COMPUTER_CASE_PRICE_FAILER";
export const UPDATE_COMPUTER_CASE_PRICE_SUCCESS = "UPDATE_COMPUTER_CASE_PRICE_SUCCESS";

export const FETCH_COMPUTER_CASE_START = "FETCH_COMPUTER_CASE_START";
export const FETCH_COMPUTER_CASE_FAILER = "FETCH_COMPUTER_CASE_FAILER";
export const FETCH_COMPUTER_CASE_SUCCESS = "FETCH_COMPUTER_CASE_SUCCESS";


export const FETCH_VIDEOCARDS_START = "FETCH_VIDEOCARDS_START";
export const FETCH_VIDEOCARDS_FAILER = "FETCH_VIDEOCARDS_FAILER";
export const FETCH_VIDEOCARDS_SUCCESS = "FETCH_VIDEOCARDS_SUCCESS";

export const GET_GLOBAL_VIDEOCARD = "GET_GLOBAL_VIDEOCARD";
export const REMOVE_GLOBAL_VIDEOCARD = "REMOVE_GLOBAL_VIDEOCARD";

export const CREATE_DEVICE_VIDEOCARD_START = "CREATE_DEVICE_VIDEOCARD_START";
export const CREATE_DEVICE_VIDEOCARD_FAILER = "CREATE_DEVICE_VIDEOCARD_FAILER";
export const CREATE_DEVICE_VIDEOCARD_SUCCESS = "CREATE_DEVICE_VIDEOCARD_SUCCESS";

export const UPDATE_VIDEOCARD_PRICE_START = "UPDATE_VIDEOCARD_PRICE_START";
export const UPDATE_VIDEOCARD_PRICE_FAILER = "UPDATE_VIDEOCARD_PRICE_FAILER";
export const UPDATE_VIDEOCARD_PRICE_SUCCESS = "UPDATE_VIDEOCARD_PRICE_SUCCESS";


export const FETCH_BASKET_DEVICES_START = "FETCH_BASKET_DEVICES_START";
export const FETCH_BASKET_DEVICES_FAILER = "FETCH_BASKET_DEVICES_FAILER";
export const FETCH_BASKET_DEVICES_SUCCESS = "FETCH_BASKET_DEVICES_SUCCESS";

export const CREATE_BASKET_DEVICES_START = "CREATE_BASKET_DEVICES_START";
export const CREATE_BASKET_DEVICES_FAILER = "CREATE_BASKET_DEVICES_FAILER";
export const CREATE_BASKET_DEVICES_SUCCESS = "CREATE_BASKET_DEVICES_SUCCESS";

export const DELETE_BASKET_DEVICES_START = "DELETE_BASKET_DEVICES_START";
export const DELETE_BASKET_DEVICES_FAILER = "DELETE_BASKET_DEVICES_FAILER";
export const DELETE_BASKET_DEVICES_SUCCESS = "DELETE_BASKET_DEVICES_SUCCESS";



export const CREATE_ORDER_START = "CREATE_ORDER_START";
export const CREATE_ORDER_FAILER = "CREATE_ORDER_FAILER";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";

export const FETCH_ORDER_START = "FETCH_ORDER_START";
export const FETCH_ORDER_FAILER = "FETCH_ORDER_FAILER";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";

export const FETCH_ONE_ORDER_START = "FETCH_ONE_ORDER_START";
export const FETCH_ONE_ORDER_FAILER = "FETCH_ONE_ORDER_FAILER";
export const FETCH_ONE_ORDER_SUCCESS = "FETCH_ONE_ORDER_SUCCESS";

export const UPDATE_ORDER_STATUS_START = "UPDATE_ORDER_STATUS_START";
export const UPDATE_ORDER_STATUS_FAILER = "UPDATE_ORDER_STATUS_FAILER";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";

export const FETCH_USER_ORDERS_START = "FETCH_USER_ORDERS_START";
export const FETCH_USER_ORDERS_FAILER = "FETCH_USER_ORDERS_FAILER";
export const FETCH_USER_ORDERS_SUCCESS = "FETCH_USER_ORDERS_SUCCESS";


export const CREATE_USER_CONFIG_DEVICE_START = "CREATE_USER_CONFIG_DEVICE_START";
export const CREATE_USER_CONFIG_DEVICE_FAILER = "CREATE_USER_CONFIG_DEVICE_FAILER";
export const CREATE_USER_CONFIG_DEVICE_SUCCESS = "CREATE_USER_CONFIG_DEVICE_SUCCESS";

export const FETCH_USER_CONFIG_DEVICE_START = "FETCH_USER_CONFIG_DEVICE_START";
export const FETCH_USER_CONFIG_DEVICE_FAILER = "FETCH_USER_CONFIG_DEVICE_FAILER";
export const FETCH_USER_CONFIG_DEVICE_SUCCESS = "FETCH_USER_CONFIG_DEVICE_SUCCESS";

export const FETCH_ONE_USER_CONFIG_DEVICE_START = "FETCH_ONE_USER_CONFIG_DEVICE_START";
export const FETCH_ONE_USER_CONFIG_DEVICE_FAILER = "FETCH_ONE_USER_CONFIG_DEVICE_FAILER";
export const FETCH_ONE_USER_CONFIG_DEVICE_SUCCESS = "FETCH_ONE_USER_CONFIG_DEVICE_SUCCESS";

export const DELETE_USER_CONFIG_DEVICE_START = "DELETE_USER_CONFIG_DEVICE_START";
export const DELETE_USER_CONFIG_DEVICE_FAILER = "DELETE_USER_CONFIG_DEVICE_FAILER";
export const DELETE_USER_CONFIG_DEVICE_SUCCESS = "DELETE_USER_CONFIG_DEVICE_SUCCESS";